# Generated by Django 6.0.3 on 2026-05-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_id', models.IntegerField()),
                ('affiliation_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.CharField(max_length=32)),
                ('contest_name', models.CharField(blank=True, max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(max_length=32, unique=True)),
                ('election_name', models.CharField(max_length=255)),
                ('election_category', models.CharField(max_length=2)),
                ('election_subcategory', models.CharField(blank=True, default='', max_length=8)),
                ('election_date', models.DateField(blank=True, null=True)),
                ('nomination_date', models.DateField(blank=True, null=True)),
                ('number_of_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('preference_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cand_id', models.IntegerField()),
                ('initials', models.CharField(blank=True, max_length=32)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('prefix', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('locality', models.CharField(blank=True, max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='uitslagenportaal.affiliation')),
            ],
        ),
        migrations.AddField(
            model_name='affiliation',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='uitslagenportaal.contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='uitslagenportaal.election'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_category', models.CharField(max_length=16)),
                ('region_number', models.CharField(max_length=16)),
                ('region_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='uitslagenportaal.election')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='uitslagenportaal.region')),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollingstation_code', models.CharField(max_length=16)),
                ('pollingstation_name', models.CharField(max_length=255)),
                ('pollingstation_zipcode', models.CharField(blank=True, max_length=16)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_stations', to='uitslagenportaal.region')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='kieskring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='uitslagenportaal.region'),
        ),
        migrations.CreateModel(
            name='ResultUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=16)),
                ('unit_id', models.CharField(blank=True, max_length=64)),
                ('unit_label', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
                ('polling_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_units', to='uitslagenportaal.pollingstation')),
                ('subregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_units', to='uitslagenportaal.region')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_valid_votes', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_results', to='uitslagenportaal.candidate')),
                ('telling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_results', to='uitslagenportaal.resultunit')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_valid_votes', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_results', to='uitslagenportaal.affiliation')),
                ('telling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_results', to='uitslagenportaal.resultunit')),
            ],
        ),
        migrations.CreateModel(
            name='Telling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telling_kind', models.CharField(max_length=16)),
                ('telling_level', models.CharField(max_length=16)),
                ('authority_id', models.CharField(blank=True, default='', max_length=64)),
                ('authority_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField()),
                ('is_current_version', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tellingen', to='uitslagenportaal.contest')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tellingen', to='uitslagenportaal.election')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tellingen', to='uitslagenportaal.region')),
            ],
        ),
        migrations.AddField(
            model_name='resultunit',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_units', to='uitslagenportaal.telling'),
        ),
        migrations.CreateModel(
            name='UnitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.IntegerField(null=True)),
                ('total_counted', models.IntegerField(null=True)),
                ('rejected_invalid', models.IntegerField(default=0)),
                ('rejected_blank', models.IntegerField(default=0)),
                ('geldige_stempassen', models.IntegerField(null=True)),
                ('geldige_volmachtbewijzen', models.IntegerField(null=True)),
                ('geldige_kiezerspassen', models.IntegerField(null=True)),
                ('toegelaten_kiezers', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_summary', to='uitslagenportaal.resultunit')),
            ],
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['election', 'region_category', 'region_number'], name='uitslagenpo_electio_cff048_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['election', 'parent'], name='uitslagenpo_electio_7ef786_idx'),
        ),
        migrations.AddIndex(
            model_name='pollingstation',
            index=models.Index(fields=['pollingstation_code'], name='uitslagenpo_polling_84f90e_idx'),
        ),
    ]
