[project]
name = "uitslagenportaal"
version = "0.1.0"
description = "TOML file for backend"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.3",
    "django-cors-headers>=4.9.0",
    "django-extensions>=4.1",
    "djangorestframework>=3.16.1",
    "psycopg2-binary>=2.9.12",
    "pyeml-bindings",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
    "tqdm>=4.68.2",
    "xsdata>=26.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.0",
    "pytest>=8.4.0",
    "pytest-django>=4.11.0",
    "factory-boy>=3.3.3",
]

[tool.setuptools]
py-modules = []

[tool.uv.sources]
pyeml-bindings = { git = "https://github.com/kiesraad/pyeml_bindings.git" }

[tool.ruff]
target-version = "py314"
line-length = 120
extend-exclude = ["*/migrations/*"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "mainsite.settings"
python_files = ["test_*.py"]
