# Generated by Django 6.0.8 on 2026-08-05 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0019_electionconfig_gh_counting_results_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_type', models.CharField(choices=[('Exchange', 'Exchange'), ('CountingResults', 'Counting results')], max_length=32)),
                ('commit_sha', models.CharField(max_length=40)),
                ('election_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_commits', to='election.electionconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
