# Generated by Django 6.0.6 on 2026-07-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
