# Generated by Django 6.0.7 on 2026-07-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_party_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='locality_name',
        ),
    ]
