# Generated by Django 6.0.7 on 2026-08-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_remove_candidate_locality_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='list_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
