# Generated by Django 6.0.8 on 2026-08-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0019_electionconfig_gh_counting_results_branch_and_more'),
        ('party', '0004_party_list_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('election', 'list_number'), name='unique_list_number_per_election'),
        ),
    ]
