# Generated by Django 6.1 on 2026-08-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0026_contest_name_alter_electionconfig_category'),
        ('party', '0005_party_unique_list_number_per_election'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('contest', 'party', 'position'), name='unique_position_per_contest_and_party'),
        ),
    ]
