# Generated by Django 6.0.8 on 2026-08-21 13:54

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0027_current_model_is_current'),
        ('party', '0006_candidate_unique_position_per_contest_and_party'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='party',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='candidate',
            name='unique_position_per_contest_and_party',
        ),
        migrations.RemoveConstraint(
            model_name='party',
            name='unique_registered_name_per_election',
        ),
        migrations.RemoveConstraint(
            model_name='party',
            name='unique_list_number_per_election',
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='party',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('contest', 'party', 'position'), name='unique_position_per_contest_and_party'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('election', 'registered_name'), name='unique_registered_name_per_election'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('election', 'list_number'), name='unique_list_number_per_election'),
        ),
    ]
