# Generated by Django 6.0.8 on 2026-08-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0031_alter_contest_options_alter_electiondocument_options_and_more'),
        ('party', '0007_current_model_is_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={},
        ),
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='party',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='candidate',
            name='unique_position_per_contest_and_party',
        ),
        migrations.RemoveConstraint(
            model_name='party',
            name='unique_registered_name_per_election',
        ),
        migrations.RemoveConstraint(
            model_name='party',
            name='unique_list_number_per_election',
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('contest', 'party', 'position'), name='unique_position_per_contest_and_party'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('election', 'registered_name'), name='unique_registered_name_per_election'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('election', 'list_number'), name='unique_list_number_per_election'),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='party',
            name='is_current',
        ),
    ]
