# Generated by Django 6.0.6 on 2026-07-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region_number', models.CharField(max_length=32)),
                ('region_category', models.CharField(choices=[('STAAT', 'Staat'), ('WATERSCHAP', 'Waterschap'), ('KIESKRING', 'Kieskring'), ('GEMEENTE', 'Gemeente'), ('PROVINCIE', 'Provincie')], max_length=32)),
                ('region_name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='election.election')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='region.region')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('election', 'slug', 'region_category'), name='unique_region_identifier_per_election')],
            },
        ),
    ]
