# Generated by Django 6.0.6 on 2026-07-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_category',
            field=models.CharField(choices=[('STAAT', 'Staat'), ('WATERSCHAP', 'Waterschap'), ('KIESKRING', 'Kieskring'), ('GEMEENTE', 'Gemeente'), ('PROVINCIE', 'Provincie'), ('STEMBUREAU', 'Stembureau')], max_length=32),
        ),
    ]
