# Generated by Django 6.0.7 on 2026-07-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_alter_region_region_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='counting_method',
            field=models.CharField(blank=True, choices=[('CSO', 'Centrale Stemopname'), ('DSO', 'Decentrale Stemopname')], max_length=3, null=True),
        ),
    ]
