# Generated by Django 6.0.7 on 2026-07-17 11:44

from django.db import migrations, models


def default_all_to_cso(apps, schema_editor):
    Region = apps.get_model("region", "Region")
    Region.objects.all().update(counting_method="CSO")


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_region_counting_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='counting_method',
            field=models.CharField(blank=True, choices=[('CSO', 'Centrale Stemopname'), ('DSO', 'Decentrale Stemopname')], default='CSO', max_length=3, null=True),
        ),
        migrations.RunPython(default_all_to_cso, migrations.RunPython.noop),
    ]
