# Generated by Django 6.0.7 on 2026-07-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0018_electionconfig_issue_report_deadline'),
        ('region', '0005_region_results_available_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='region',
            name='unique_region_identifier_per_election',
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('election', 'slug', 'region_category', 'parent'), name='unique_region_identifier_per_election'),
        ),
    ]
