# Generated by Django 6.0.7 on 2026-08-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0005_region_results_available_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_number',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
