# Generated by Django 6.0.7 on 2026-08-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0006_alter_region_region_number'),
        ('region', '0006_remove_region_unique_region_identifier_per_election_and_more'),
    ]

    operations = [
    ]
