# Generated by Django 6.0.7 on 2026-08-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0008_region_csb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='counting_method',
            field=models.CharField(blank=True, choices=[('CSO', 'Centrale Stemopname'), ('DSO', 'Decentrale Stemopname')], max_length=3, null=True),
        ),
    ]
