# Generated by Django 6.0.8 on 2026-08-21 13:54

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0027_current_model_is_current'),
        ('region', '0009_alter_region_counting_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='region',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='region',
            name='unique_region_identifier_per_election',
        ),
        migrations.AddField(
            model_name='region',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('election', 'slug', 'region_category', 'parent'), name='unique_region_identifier_per_election'),
        ),
    ]
