# Generated by Django 6.0.8 on 2026-08-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0031_alter_contest_options_alter_electiondocument_options_and_more'),
        ('region', '0010_current_model_is_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelManagers(
            name='region',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='region',
            name='unique_region_identifier_per_election',
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('election', 'slug', 'region_category', 'parent'), name='unique_region_identifier_per_election'),
        ),
        migrations.RemoveField(
            model_name='region',
            name='is_current',
        ),
    ]
