# Generated by Django 6.0.6 on 2026-07-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=8)),
                ('identifier', models.CharField(max_length=64)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(max_length=2)),
                ('label', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_votes', models.PositiveIntegerField()),
                ('result_level', models.CharField(choices=[('PARTY', 'Party'), ('CANDIDATE', 'Candidate')], default='CANDIDATE', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(blank=True, max_length=255)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='election.election')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='election',
            name='election_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='election.electionconfig'),
        ),
        migrations.CreateModel(
            name='ElectionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In progress'), ('done', 'Done')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
                ('election_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='election.electionconfig')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
