# Generated by Django 6.0.6 on 2026-07-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0001_initial'),
        ('party', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votecount',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pollingstation_results', to='party.candidate'),
        ),
        migrations.AddField(
            model_name='votecount',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='election.contest'),
        ),
        migrations.AddField(
            model_name='votecount',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollingstation_results', to='party.party'),
        ),
        migrations.AddField(
            model_name='votecount',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='region.region'),
        ),
        migrations.AddConstraint(
            model_name='electionstep',
            constraint=models.UniqueConstraint(fields=('election_config', 'position'), name='unique_step_position_per_election'),
        ),
    ]
