# Generated by Django 6.0.6 on 2026-07-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='identifier',
        ),
    ]
