# Generated by Django 6.0.6 on 2026-07-08 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_remove_election_identifier'),
        ('party', '0001_initial'),
        ('region', '0002_alter_region_region_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecount',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_counts', to='party.candidate'),
        ),
        migrations.AlterField(
            model_name='votecount',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_counts', to='election.contest'),
        ),
        migrations.AlterField(
            model_name='votecount',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_counts', to='party.party'),
        ),
        migrations.AlterField(
            model_name='votecount',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_counts', to='region.region'),
        ),
    ]
