# Generated by Django 6.0.6 on 2026-07-08 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0004_alter_votecount_candidate_alter_votecount_contest_and_more"),
        ("region", "0002_alter_region_region_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoterTurnoutCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cast", models.PositiveIntegerField(blank=True, null=True)),
                ("total_counted", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("REJECTED", "Rejected votes"),
                            ("UNCOUNTED", "Uncounted votes"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason_code", models.CharField(max_length=64)),
                ("votes", models.PositiveIntegerField()),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voter_turnout_counts",
                        to="election.contest",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voter_turnout_counts",
                        to="region.region",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
