# Generated by Django 6.0.6 on 2026-07-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_voterturnoutcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterturnoutcount',
            name='category',
            field=models.CharField(choices=[('REJECTED', 'Rejected votes'), ('UNCOUNTED', 'Uncounted votes'), ('TOTALS', 'Total votes')], max_length=16),
        ),
    ]
