# Generated by Django 6.0.6 on 2026-07-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_alter_voterturnoutcount_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterturnoutcount',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='voterturnoutcount',
            name='total_counted',
        ),
    ]
