# Generated by Django 6.0.7 on 2026-07-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_remove_voterturnoutcount_cast_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electionstep',
            options={'ordering': ('date',)},
        ),
    ]
