# Generated by Django 6.0.7 on 2026-07-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_rename_electionstep_timelineentry'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timelineentry',
            name='unique_step_position_per_election',
        ),
        migrations.RemoveField(
            model_name='timelineentry',
            name='position',
        ),
    ]
