# Generated by Django 6.0.7 on 2026-07-15 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_remove_timelineentry_unique_step_position_per_election_and_more'),
        ('region', '0002_alter_region_region_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('content_type', models.CharField(default='application/xml', max_length=128)),
                ('size', models.PositiveIntegerField()),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='region.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
