# Generated by Django 6.0.7 on 2026-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_remove_timelineentry_unique_step_position_per_election_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='variant',
            field=models.CharField(choices=[('CSO', 'Centrale Stemopname'), ('DSO', 'Decentrale Stemopname'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=8),
        ),
    ]
