# Generated by Django 6.0.7 on 2026-07-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_electiondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiondocument',
            name='file_type',
            field=models.CharField(choices=[('EML510b', 'EML510b')], default='EML510b', help_text='Type of the election document', max_length=32),
        ),
    ]
