# Generated by Django 6.0.7 on 2026-07-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_electiondocument_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='votecount',
            name='eml_type',
            field=models.CharField(choices=[('EML510b', 'EML510b'), ('EML510d', 'EML510d')], max_length=32, null=True),
        ),
    ]
