# Generated by Django 6.0.7 on 2026-07-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_timelineentry_variant'),
        ('election', '0013_votecount_eml_type'),
    ]

    operations = [
    ]
