# Generated by Django 6.0.7 on 2026-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_votecount_eml_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionconfig',
            name='csb_type',
            field=models.CharField(blank=True, choices=[('STAAT', 'Staat'), ('WATERSCHAP', 'Waterschap'), ('KIESKRING', 'Kieskring'), ('GEMEENTE', 'Gemeente'), ('PROVINCIE', 'Provincie'), ('STEMBUREAU', 'Stembureau')], max_length=32, null=True),
        ),
    ]
