# Generated by Django 6.0.7 on 2026-07-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0014_electionconfig_csb_type'),
        ('election', '0014_merge_20260720_1237'),
    ]

    operations = [
    ]
