# Generated by Django 6.0.7 on 2026-07-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0015_merge_20260720_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionconfig',
            name='csb_type',
        ),
    ]
