# Generated by Django 6.0.7 on 2026-08-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0018_electionconfig_issue_report_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterturnoutcount',
            name='eml_type',
            field=models.CharField(choices=[('EML510b', 'EML510b'), ('EML510d', 'EML510d')], max_length=32, null=True),
        ),
    ]
