# Generated by Django 6.0.7 on 2026-08-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0018_electionconfig_issue_report_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionconfig',
            name='counting_info_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='electionconfig',
            name='report_error_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='electionconfig',
            name='voting_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
