# Generated by Django 6.0.7 on 2026-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0019_voterturnoutcount_eml_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecount',
            name='eml_type',
            field=models.CharField(choices=[('510b', '510b'), ('510d', '510d')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='voterturnoutcount',
            name='eml_type',
            field=models.CharField(choices=[('510b', '510b'), ('510d', '510d')], max_length=32, null=True),
        ),
    ]
