# Generated by Django 6.0.7 on 2026-08-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0019_electionconfig_counting_info_url_and_more'),
        ('election', '0020_alter_eml_type_choices'),
    ]

    operations = [
    ]
