# Generated by Django 6.0.8 on 2026-08-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0022_electionconfig_gh_counting_results_branch_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.UniqueConstraint(fields=('election', 'identifier'), name='unique_contest_identifier_per_election'),
        ),
    ]
