# Generated by Django 6.0.7 on 2026-08-11 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0022_electionconfig_gh_counting_results_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionconfig',
            name='issue_report_opens_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 12, 8, 8, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
