# Generated by Django 6.0.7 on 2026-08-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0023_contest_unique_contest_identifier_per_election'),
        ('election', '0023_electionconfig_issue_report_opens_at'),
    ]

    operations = [
    ]
