# Generated by Django 6.1 on 2026-08-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0024_merge_20260811_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiondocument',
            name='file_type',
            field=models.CharField(choices=[('EML510b', 'Eml510B')], default='EML510b', help_text='Type of the election document', max_length=32),
        ),
    ]
