# Generated by Django 6.1 on 2026-08-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0024_merge_20260811_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electionconfig',
            name='category',
            field=models.CharField(choices=[('TK', 'Tweede Kamerverkiezing'), ('EK', 'Eerste Kamerverkiezing'), ('PS', 'Provinciale Statenverkiezing'), ('WS', 'Waterschapsverkiezing'), ('GR', 'Gemeenteraadsverkiezing'), ('EP', 'Europees Parlementsverkiezing')], max_length=2),
        ),
    ]
