# Generated by Django 6.1 on 2026-08-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0024_merge_20260811_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiondocument',
            name='file_type',
            field=models.CharField(choices=[('EML510b', 'Eml510B')], default='EML510b', help_text='Type of the election document', max_length=32),
        ),
        migrations.AlterField(
            model_name='votecount',
            name='eml_type',
            field=models.CharField(choices=[('110a', 'Verkiezingsdefinitie'), ('110b', 'Stembureaus'), ('230b', 'Kandidatenlijsten'), ('510a', 'Telling SB'), ('510b', 'Telling GSB'), ('510c', 'Totaaltelling HSB'), ('510d', 'Totaaltelling CSB'), ('520', 'Resultaat')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='voterturnoutcount',
            name='eml_type',
            field=models.CharField(choices=[('110a', 'Verkiezingsdefinitie'), ('110b', 'Stembureaus'), ('230b', 'Kandidatenlijsten'), ('510a', 'Telling SB'), ('510b', 'Telling GSB'), ('510c', 'Totaaltelling HSB'), ('510d', 'Totaaltelling CSB'), ('520', 'Resultaat')], max_length=32, null=True),
        ),
    ]
