# Generated by Django 6.0.8 on 2026-08-21 13:54

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0026_contest_name_alter_electionconfig_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='votecount',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='voterturnoutcount',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='contest',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='votecount',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='voterturnoutcount',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='contest',
            name='unique_contest_identifier_per_election',
        ),
        migrations.AddField(
            model_name='contest',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='votecount',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='voterturnoutcount',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('election', 'identifier'), name='unique_contest_identifier_per_election'),
        ),
    ]
