# Generated by Django 6.0.8 on 2026-08-27 08:33

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0026_contest_name_alter_electionconfig_category'),
        ('region', '0009_alter_region_counting_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electiondocument',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='electiondocument',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='electiondocument',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='electiondocument',
            name='file_type',
            field=models.CharField(choices=[('110a', 'Verkiezingsdefinitie'), ('110b', 'Stembureaus'), ('230b', 'Kandidatenlijsten'), ('510a', 'Telling SB'), ('510b', 'Telling GSB'), ('510c', 'Totaaltelling HSB'), ('510d', 'Totaaltelling CSB'), ('520', 'Resultaat')], default='510b', help_text='Type of the election document', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='electiondocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('region', 'file_type'), name='unique_current_document_per_region_and_file_type'),
        ),
    ]
