# Generated by Django 6.0.8 on 2026-08-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0027_alter_electiondocument_options_and_more'),
        ('election', '0027_delete_cast_voter_turnout_counts'),
    ]

    operations = [
    ]
