# Generated by Django 6.0.8 on 2026-09-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("election", "0027_delete_cast_voter_turnout_counts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timelineentry",
            old_name="body",
            new_name="body_nl",
        ),
        migrations.RenameField(
            model_name="timelineentry",
            old_name="title",
            new_name="title_nl",
        ),
        migrations.AddField(
            model_name="timelineentry",
            name="body_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="timelineentry",
            name="title_en",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
