# Generated by Django 6.0.8 on 2026-09-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("election", "0028_merge_20260827_1038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electiondocument",
            name="file_type",
            field=models.CharField(
                choices=[("510b", "Telling GSB"), ("510d", "Totaaltelling CSB")],
                default="510b",
                help_text="Type of the election document",
                max_length=32,
            ),
        ),
    ]
