# Generated by Django 6.0.8 on 2026-08-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0028_electiondocument_is_current"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electiondocument",
            name="file_type",
            field=models.CharField(
                choices=[("EML510b", "Eml510B"), ("EML510d", "Eml510D")],
                default="EML510b",
                help_text="Type of the election document",
                max_length=32,
            ),
        ),
    ]
