# Generated by Django 6.0.8 on 2026-08-26 10:35

from django.db import migrations, models


def forward_align_file_types(apps, schema_editor):
    ElectionDocument = apps.get_model("election", "ElectionDocument")
    ElectionDocument.objects.filter(file_type="EML510b").update(file_type="510b")
    ElectionDocument.objects.filter(file_type="EML510d").update(file_type="510d")


def reverse_align_file_types(apps, schema_editor):
    ElectionDocument = apps.get_model("election", "ElectionDocument")
    ElectionDocument.objects.filter(file_type="510b").update(file_type="EML510b")
    ElectionDocument.objects.filter(file_type="510d").update(file_type="EML510d")


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0029_electiondocument_file_type_eml510d"),
    ]

    operations = [
        migrations.RunPython(forward_align_file_types, reverse_align_file_types),
        migrations.AlterField(
            model_name="electiondocument",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("110a", "Verkiezingsdefinitie"),
                    ("110b", "Stembureaus"),
                    ("230b", "Kandidatenlijsten"),
                    ("510a", "Telling SB"),
                    ("510b", "Telling GSB"),
                    ("510c", "Totaaltelling HSB"),
                    ("510d", "Totaaltelling CSB"),
                    ("520", "Resultaat"),
                ],
                default="510b",
                help_text="Type of the election document",
                max_length=32,
            ),
        ),
    ]
