# Generated by Django 6.0.8 on 2026-09-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0028_timeline_entry_title_body_locales'),
        ('election', '0029_alter_electiondocument_file_type'),
    ]

    operations = [
    ]
