# Generated by Django 6.0.8 on 2026-08-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0030_align_electiondocument_file_type_with_eml_type'),
        ('region', '0010_current_model_is_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='electiondocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='votecount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='voterturnoutcount',
            options={},
        ),
        migrations.AlterModelManagers(
            name='contest',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='electiondocument',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='votecount',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='voterturnoutcount',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='contest',
            name='unique_contest_identifier_per_election',
        ),
        migrations.RemoveConstraint(
            model_name='electiondocument',
            name='unique_current_document_per_region_and_file_type',
        ),
        migrations.RemoveField(
            model_name='votecount',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='voterturnoutcount',
            name='is_current',
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.UniqueConstraint(fields=('election', 'identifier'), name='unique_contest_identifier_per_election'),
        ),
        migrations.AddConstraint(
            model_name='electiondocument',
            constraint=models.UniqueConstraint(fields=('region', 'file_type'), name='unique_current_document_per_region_and_file_type'),
        ),
        migrations.RemoveField(
            model_name='contest',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='electiondocument',
            name='is_current',
        ),
    ]
