# Generated by Django 6.0.8 on 2026-08-27 08:15

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0031_alter_contest_options_alter_electiondocument_options_and_more'),
        ('region', '0011_alter_region_options_alter_region_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electiondocument',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='electiondocument',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='electiondocument',
            name='unique_current_document_per_region_and_file_type',
        ),
        migrations.AddField(
            model_name='electiondocument',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='electiondocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('region', 'file_type'), name='unique_current_document_per_region_and_file_type'),
        ),
    ]
