# Generated by Django 6.0.8 on 2026-09-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0030_merge_20260908_1334'),
        ('election', '0031_alter_electiondocument_file_type'),
    ]

    operations = [
    ]
