# Generated by Django 6.0.8 on 2026-09-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0032_merge_20260908_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiondocument',
            name='file_type',
            field=models.CharField(choices=[('EML510b', 'Telling GSB'), ('EML510c', 'Totaaltelling HSB'), ('EML510d', 'Totaaltelling CSB')], default='EML510b', help_text='Type of the election document', max_length=32),
        ),
    ]
