# Generated by Django 6.1.1 on 2026-09-24 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0033_alter_electiondocument_file_type'),
        ('region', '0009_alter_region_counting_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertifiedElectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.PositiveIntegerField()),
                ('file_type', models.CharField(choices=[('N10-1', 'Proces-verbaal stembureau'), ('N10-2', 'Proces-verbaal stembureau in een gemeente die CSB is'), ('NA14-1', 'Corrigendum proces-verbaal stembureau'), ('NA31-1', 'Proces-verbaal gemeentelijk stembureau (DSO)'), ('NA31-2', 'Proces-verbaal gemeentelijk stembureau (CSO)'), ('NA14-2', 'Corrigendum proces-verbaal gemeentelijk stembureau'), ('O7', 'Proces-verbaal hoofdstembureau'), ('P22-1', 'Proces-verbaal centraal stembureau met meerdere kieskringen'), ('P22-2', 'Proces-verbaal centraal stembureau met één kieskring')], max_length=16)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('content_type', models.CharField(default='application/pdf', max_length=128)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certified_election_documents', to='region.region')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('region', 'file_type'), name='unique_current_certified_document_per_region_and_code')],
            },
        ),
    ]
