# Generated by Django 6.0.8 on 2026-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0033_alter_electiondocument_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionconfig',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
