# Generated by Django 6.1.1 on 2026-09-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0033_alter_electiondocument_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiondocument',
            name='file_type',
            field=models.CharField(choices=[('EML110a', 'Verkiezingsdefinitie'), ('EML230b', 'Kandidatenlijst'), ('EML510b', 'Telling GSB'), ('EML510c', 'Totaaltelling HSB'), ('EML510d', 'Totaaltelling CSB'), ('CSV_OSV4-3', 'OSV4-3 telling CSV')], default='EML510b', help_text='Type of the election document', max_length=32),
        ),
    ]
