# Generated by Django 6.1.1 on 2026-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0034_certifiedelectiondocument'),
        ('region', '0009_alter_region_counting_method'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certifiedelectiondocument',
            name='unique_current_proces_verbaal_per_region_and_code',
        ),
        migrations.AddConstraint(
            model_name='certifiedelectiondocument',
            constraint=models.UniqueConstraint(fields=('region', 'file_type'), name='unique_current_certified_document_per_region_and_code'),
        ),
    ]
