# Generated by Django 6.1.1 on 2026-09-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0034_alter_electiondocument_file_type'),
        ('election', '0034_electionconfig_source_hash'),
    ]

    operations = [
    ]
