# Generated by Django 6.1.1 on 2026-09-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0034_certifiedelectiondocument'),
        ('election', '0035_merge_20260917_1317'),
    ]

    operations = [
    ]
