# Generated by Django 6.1.1 on 2026-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0035_merge_20260917_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiondocument',
            name='file_type',
            field=models.CharField(choices=[('EML110a', 'Verkiezingsdefinitie'), ('EML230b', 'Kandidatenlijst'), ('EML510b', 'Telling GSB'), ('EML510c', 'Totaaltelling HSB'), ('EML510d', 'Totaaltelling CSB'), ('CSV_OSV4-3', 'OSV4-3 telling CSV'), ('PDF_N10-1', 'Proces-verbaal stembureau'), ('PDF_N10-2', 'Proces-verbaal stembureau in een gemeente die CSB is'), ('PDF_NA14-1', 'Corrigendum proces-verbaal stembureau'), ('PDF_NA31-1', 'Proces-verbaal gemeentelijk stembureau (DSO)'), ('PDF_NA31-2', 'Proces-verbaal gemeentelijk stembureau (CSO)'), ('PDF_NA14-2', 'Corrigendum proces-verbaal gemeentelijk stembureau'), ('PDF_O7', 'Proces-verbaal hoofdstembureau'), ('PDF_P22-1', 'Proces-verbaal centraal stembureau met meerdere kieskringen'), ('PDF_P22-2', 'Proces-verbaal centraal stembureau met één kieskring')], default='EML510b', help_text='Type of the election document', max_length=32),
        ),
    ]
