# Generated by Django 6.0.8 on 2026-10-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0036_alter_electiondocument_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionconfig',
            name='category',
            field=models.CharField(choices=[('TK', 'Tweede Kamerverkiezing'), ('PS', 'Provinciale Statenverkiezing'), ('WS', 'Waterschapsverkiezing'), ('GR', 'Gemeenteraadsverkiezing'), ('EP', 'Europees Parlementsverkiezing')], max_length=2),
        ),
    ]
