# Generated by Django 6.0.8 on 2026-10-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0037_alter_electionconfig_category'),
        ('region', '0009_alter_region_counting_method'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='electiondocument',
            name='unique_current_document_per_region_and_file_type',
        ),
        migrations.AddConstraint(
            model_name='electiondocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), models.Q(('file_type__in', ('PDF_NA14-1', 'PDF_NA14-2')), _negated=True)), fields=('region', 'file_type'), name='unique_current_document_per_region_and_file_type'),
        ),
    ]
