app:
  hostname: "uitslagenportaal-staging.kiesraad.net"

backend:
  # todo: revert to :main
  image: "ghcr.io/kiesraad/uitslagenportaal-backend:276-add-staging-deploy"

frontend:
  # todo: revert to :main
  image: "ghcr.io/kiesraad/uitslagenportaal-frontend:276-add-staging-deploy"

celery:
  # todo: revert to :main
  image: "ghcr.io/kiesraad/uitslagenportaal-backend:276-add-staging-deploy"
