# Generated by Django 6.0.8 on 2026-10-01 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('kind', models.CharField(choices=[('STAAT', 'Staat'), ('WATERSCHAP', 'Waterschap'), ('KIESKRING', 'Kieskring'), ('GEMEENTE', 'Gemeente'), ('PROVINCIE', 'Provincie'), ('STEMBUREAU', 'Stembureau')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('election_pages', models.JSONField(blank=True, default=list)),
                ('exclude', models.CharField(blank=True, max_length=255, null=True)),
                ('cookie_banner_label', models.CharField(blank=True, max_length=255, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('scrape_requested_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('running', 'Running'), ('ok', 'OK'), ('no-pvs-found', 'No PVs found'), ('gone', 'Gone'), ('blocked', 'Blocked'), ('error', 'Error')], max_length=16, null=True)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('rejected', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.CharField(blank=True, max_length=64, null=True)),
                ('model', models.CharField(blank=True, max_length=32, null=True)),
                ('url', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified', models.CharField(blank=True, max_length=64, null=True)),
                ('link_text', models.TextField(blank=True)),
                ('heading_text', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_files', to='pv_scraper.scrapesource')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'url'], name='scrapedfile_source_url')],
                'constraints': [models.UniqueConstraint(fields=('source', 'sha256'), name='unique_sha256_per_source')],
            },
        ),
    ]
