# Generated by Django 6.0.8 on 2026-10-08 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapesource',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='scrapesource',
            name='rejected',
        ),
        migrations.AddField(
            model_name='scrapedfile',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='scrapesource',
            name='last_run_status',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('running', 'Running'), ('ok', 'OK'), ('no-pvs-found', 'No PVs found'), ('gone', 'Gone'), ('blocked', 'Blocked'), ('error', 'Error')], max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField()),
                ('via', models.TextField(blank=True, null=True)),
                ('root', models.TextField()),
                ('depth', models.PositiveSmallIntegerField()),
                ('status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('links', models.PositiveIntegerField(blank=True, null=True)),
                ('files', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('last_file_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_pages', to='pv_scraper.scrapesource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'url'), name='unique_page_url_per_source')],
            },
        ),
    ]
