name: CD
on:
  push:
#    branches:
#      - dev

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  artifact-metadata: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-frontend-image:
    name: Publish Frontend Image
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      context: frontend
  publish-backend-image:
    name: Publish Backend Image
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      context: backend
