name: Publish Docker Images
on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
        description: Directory to build the image from

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-${{ inputs.context }}

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push the image
      - name: Build and push
        id: push
        uses: docker/build-push-action@v7
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/prod.dockerfile
          platforms: linux/amd64
          push: true
          # For now, we only push dev images, but later we will use the version from a git tag for the main branch.
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

      # This step generates an artefact attestation for the image,
      # which is an unforgeable statement about where and how it was built.
      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
